# Arrays

### Arrays são estruturas de dados multidimensionais da biblioteca Numpy que armazenam um único tipo de dado. O funcionamento de uma array é baseado em um nível mais baixo do que as estruturas nativas do Python, sendo otimizada para funções matemáticas comuns entre matrizes de dados.

## Bibliotecas

In [1]:
import numpy as np

## Métodos construtivos de Arrays

### np.array()
#### Cria uma array.

In [2]:
# Criando uma array 1x3 de maneira usual.
arr1 = np.array([[1, 2, 3]])
arr1

array([[1, 2, 3]])

In [3]:
# Criando uma array 3x1 e definindo seu tipo com dtype.
arr2 = np.array([1, 2, 3], dtype=str)
arr2

array(['1', '2', '3'], dtype='<U1')

In [4]:
# É possível criar uma array a partir de outra estrutura de dados, uma tupla por exemplo.
t = ((1, 2, 3), (4, 5, 6), (7, 8, 9))
arr3 = np.array(t) # Dimensão 3x3.
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### np.full(dimensão, n)
#### Cria uma array de valores iguais a n.

In [5]:
arr4 = np.full((2, 4), 1) 
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### np.full_like(dado, n)
#### Copia a dimensão de um dado e substitui todos os seus valores por n.

In [6]:
arr5 = np.full_like(arr4, 2)
arr5

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### np.eye(dimensão)
#### Cria uma matriz identidade com a dimensão especificada.

In [7]:
arr6 = np.eye(4)
arr6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### dado.astype(tipo)
#### Cria uma array a partir de um dado, com o tipo especificado.

In [8]:
arr7 = arr6.astype(str)
arr7

array([['1.0', '0.0', '0.0', '0.0'],
       ['0.0', '1.0', '0.0', '0.0'],
       ['0.0', '0.0', '1.0', '0.0'],
       ['0.0', '0.0', '0.0', '1.0']], dtype='<U32')

### np.arange(n)
#### Funciona como o range() do Python. Cria uma array nx1 indo de 0 até (n - 1).

In [9]:
arr8 = np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.random.rand(n)
#### Cria uma array com n valores positivos pertencentes à distribuição normal de desvio padrão 1 e média 0.

In [10]:
arr9 = np.random.rand(20)
arr9

array([0.0986764 , 0.69875089, 0.04933496, 0.197107  , 0.25704108,
       0.90002557, 0.48917581, 0.46883076, 0.22911764, 0.50934026,
       0.43534008, 0.59083724, 0.88981074, 0.97295653, 0.5740627 ,
       0.82217355, 0.44228725, 0.39577211, 0.07108059, 0.60885594])

### np.random.randn(n)
#### Faz o mesmo que o método anterior, mas agora valores negativos também serão escolhidos.

In [11]:
arr10 = np.random.randn(12)
arr10

array([ 0.83429264,  0.74186803,  0.69985913, -1.487009  , -0.09688481,
        0.78347656,  0.52668533,  0.36383321,  1.50956084,  1.22761428,
       -1.05334284, -0.30188628])

### np.random.normal(m, d, size=n)
#### Cria uma array com n elementos da distribuição normal com média m e desvio padrão d.

In [12]:
arr11 = np.random.normal(10, 2, size=15)
arr11

array([ 6.40892705, 10.15605851,  9.66856957,  9.51122265,  6.86086852,
       10.04986665,  8.58140562,  8.94332063, 12.6184079 ,  7.19031525,
        6.77686376,  9.2523521 , 11.88826144, 14.17284696, 14.89941452])

In [13]:
arr12 = np.random.normal(15, 3, size=100000)
mean = np.mean(arr12) # np.mean(arr) calcula a média de arr.
std = np.std(arr12) # np.std(arr) calcula o desvio padrão de arr.

print(f'Média: {round(mean, 0)}, Desvio Padrão: {round(std, 0)}') # Prova real.
# round(v, d) arredonda v para d casas decimais.

Média: 15.0, Desvio Padrão: 3.0


### np.random.randint(m, size=n)
#### Cria uma array com n números inteiros, variando de 0 até m.

In [14]:
arr13 = np.random.randint(30, size=50)
arr13

array([12,  9, 25, 20, 22,  5, 29,  8, 19, 15, 14,  9,  2, 27, 16,  7, 15,
       17, 10, 11, 24,  7,  0, 14, 29,  4,  2, 18,  3, 28, 16,  8, 20,  6,
       22,  6, 16, 20,  2, 28, 14,  4,  9, 28,  1, 16, 28,  6,  6, 10])

### np.random.permutation(n)
#### Cria uma array com n valores permutados variando de 0 a n-1.

In [15]:
arr14 = np.random.permutation(10)
arr14

array([3, 2, 6, 4, 9, 0, 8, 7, 5, 1])

-------------------------------------------------------------------------------------------------------

## Redimensionamento

### reshape(n1, n2, n3, ...nm)
#### Redimensiona a instância que o está chamando. Para que reshape funcione o produto n1 x n2 x ... x nm deve ser igual ao número de elementos da instância.

In [16]:
arr15 = arr8.reshape(5, 2) # arr8 tem 10 elementos (5 x 2 = 10).
arr15

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

### flatten()
#### Lineariza a instância.

In [17]:
arr15.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

-------------------------------------------------------------------------------------------------------

## Condicionais e Mapeamento

### Condição como indexação

In [18]:
# A condição arr8 > 3 retorna uma array booleana, sendo True para os valores maiores que três e False para
# os menores. A partir dessa array booleana, que representa nossa condição, vamos indexar uma nova array.
b = arr8 > 3
b

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [19]:
arr8 = arr8[b]
arr8

array([4, 5, 6, 7, 8, 9])

### np.where(cond, arr1, arr2)
#### O método where se baseará na matriz booleana cond. Se o valor for True, então o valor posicional correspondente será selecionado da array arr1, caso contrário, será selecionado de arr2.

In [20]:
arr16 = np.array([1, 2, 3, 4, 5])
arr17 = np.array([6, 7 , 8, 9, 10])
cond = np.array([True, True, False, False, True])

arr18 = np.where(cond, arr16, arr17)
arr18

array([1, 2, 8, 9, 5])

### arr[map]
#### Mapeia os valores de arr nos valores de map

In [21]:
arr19 = np.array(['São Paulo', 'Rio de Janeiro', 'Minas Gerais'])
arr19

array(['São Paulo', 'Rio de Janeiro', 'Minas Gerais'], dtype='<U14')

In [22]:
arr19[[0, 1, 2, 1, 2, 0]]

array(['São Paulo', 'Rio de Janeiro', 'Minas Gerais', 'Rio de Janeiro',
       'Minas Gerais', 'São Paulo'], dtype='<U14')

-------------------------------------------------------------------------------------------------------

## Indexação

### Indexação de colunas: arr[:, [colunas]]

In [23]:
arr20 = np.arange(16).reshape(4, 4)
arr20

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
arr20[:, [0, 3]] # Retornará a primeira e a terceira coluna, lembrando que a primeira coluna está indexada com a posição 0.

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15]])

### Indexação de linhas: arr[[linhas]]

In [25]:
arr20[[1, 2]] # Retornará a segunda e terceira linha.

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Indexação de linhas e colunas: arr[linha1:linha2, coluna1:coluna2]

In [26]:
arr20[1:3, 2:]

array([[ 6,  7],
       [10, 11]])

### Indexação de linhas alterando a ordem das colunas: arr[linhas][:, [colunas]]

In [27]:
arr20[[0, 2]][:, [0, 2, 1, 3]]

array([[ 0,  2,  1,  3],
       [ 8, 10,  9, 11]])

### Indexação de colunas alterando a ordem das linhas: arr[:, [colunas]][[linhas]]

In [28]:
arr20[:, [2, 3]][[3, 2, 0, 1]]

array([[14, 15],
       [10, 11],
       [ 2,  3],
       [ 6,  7]])

### Indexação de um único elemento: arr[linha, coluna]

In [29]:
arr20[3, 2] # Elemento na quarta linha e terceira coluna.

14

-------------------------------------------------------------------------------------------------------

## Mudança de Eixos

### transpose(eixo 1, eixo 2, ... , eixo n)
#### Define os novos eixos na ordem em que os parâmetros foram passados.

In [30]:
arr4

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [31]:
arr4.transpose(1, 0) 
# O eixo 1 (das colunas) passa a ser o novo eixo das linhas, e o eixo 0 (das linhas) passa a ser o novo 
# eixo das colunas.

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

### swapaxes(eixo 1, eixo 2)
#### Inverte a ordem dos eixos 1 e 2.

In [32]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr3.swapaxes(1, 0) # arr.swapaxes(1, 0) é igual a arr.swapaxes(0, 1) que é igual à transposta de arr.

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

-------------------------------------------------------------------------------------------------------

## Métodos Estatísticos de alto nível

### np.var(arr)
#### Calcula a variância de arr.

In [34]:
arr21 = np.random.randint(15, size=40)
arr21

array([ 9, 11,  7,  5,  8, 13,  7,  1,  7,  5, 11,  7, 13, 14,  2,  2, 12,
        5,  8,  6, 14, 11,  4,  8,  9,  0, 12,  2, 14,  7, 11,  7,  8,  9,
       13,  7,  7,  8,  6,  2])

In [35]:
np.var(arr21)

14.209999999999999

### np.mean(arr)
#### Calcula a média de arr.

In [36]:
np.mean(arr21)

7.8

### np.max(arr)
#### Exibe o maior valor de arr.

In [37]:
np.max(arr21)

14

### np.abs(arr)
#### Calcula o módulo de todos os elementos de arr.

In [38]:
arr10

array([ 0.83429264,  0.74186803,  0.69985913, -1.487009  , -0.09688481,
        0.78347656,  0.52668533,  0.36383321,  1.50956084,  1.22761428,
       -1.05334284, -0.30188628])

In [39]:
np.abs(arr10)

array([0.83429264, 0.74186803, 0.69985913, 1.487009  , 0.09688481,
       0.78347656, 0.52668533, 0.36383321, 1.50956084, 1.22761428,
       1.05334284, 0.30188628])

### np.sqrt(arr)
#### Calcula a raiz quadrada de todos os elementos de arr.

In [40]:
np.sqrt(arr21)

array([3.        , 3.31662479, 2.64575131, 2.23606798, 2.82842712,
       3.60555128, 2.64575131, 1.        , 2.64575131, 2.23606798,
       3.31662479, 2.64575131, 3.60555128, 3.74165739, 1.41421356,
       1.41421356, 3.46410162, 2.23606798, 2.82842712, 2.44948974,
       3.74165739, 3.31662479, 2.        , 2.82842712, 3.        ,
       0.        , 3.46410162, 1.41421356, 3.74165739, 2.64575131,
       3.31662479, 2.64575131, 2.82842712, 3.        , 3.60555128,
       2.64575131, 2.64575131, 2.82842712, 2.44948974, 1.41421356])

### np.square(arr)
#### Calcula a segunda potência de todos os valores de arr.

In [41]:
np.square(arr21)

array([ 81, 121,  49,  25,  64, 169,  49,   1,  49,  25, 121,  49, 169,
       196,   4,   4, 144,  25,  64,  36, 196, 121,  16,  64,  81,   0,
       144,   4, 196,  49, 121,  49,  64,  81, 169,  49,  49,  64,  36,
         4])

### np.log10(arr)
#### Calcula o logaritmo de base 10 de todos os valores de arr.

In [42]:
arr21[arr21 == 0] = 1 # Trocando os 0's por 1's pois não existe logaritmo de números menores ou iguais a 0.
np.log10(arr21)

array([0.95424251, 1.04139269, 0.84509804, 0.69897   , 0.90308999,
       1.11394335, 0.84509804, 0.        , 0.84509804, 0.69897   ,
       1.04139269, 0.84509804, 1.11394335, 1.14612804, 0.30103   ,
       0.30103   , 1.07918125, 0.69897   , 0.90308999, 0.77815125,
       1.14612804, 1.04139269, 0.60205999, 0.90308999, 0.95424251,
       0.        , 1.07918125, 0.30103   , 1.14612804, 0.84509804,
       1.04139269, 0.84509804, 0.90308999, 0.95424251, 1.11394335,
       0.84509804, 0.84509804, 0.90308999, 0.77815125, 0.30103   ])

### np.sign(arr)
#### Retorna uma array de 1's e -1's de acordo com os sinais dos valores de arr.

In [43]:
np.sign(arr10)

array([ 1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.,  1., -1., -1.])

### np.ceil(arr)
#### Arrendonda os valores de arr para cima.

In [44]:
arr11

array([ 6.40892705, 10.15605851,  9.66856957,  9.51122265,  6.86086852,
       10.04986665,  8.58140562,  8.94332063, 12.6184079 ,  7.19031525,
        6.77686376,  9.2523521 , 11.88826144, 14.17284696, 14.89941452])

In [45]:
np.ceil(arr11)

array([ 7., 11., 10., 10.,  7., 11.,  9.,  9., 13.,  8.,  7., 10., 12.,
       15., 15.])

### np.floor(arr)
#### Arrendonda os valores de arr para baixo.

In [46]:
np.floor(arr11)

array([ 6., 10.,  9.,  9.,  6., 10.,  8.,  8., 12.,  7.,  6.,  9., 11.,
       14., 14.])

### np.isnan(arr)
#### Retorna uma matriz booleana com True para os valores que são NaN (não disponível/não numérico).

In [47]:
np.log10(arr10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([-0.07868159, -0.12967334, -0.15498937,         nan,         nan,
       -0.10597399, -0.27844878, -0.43909766,  0.17885062,  0.08906193,
               nan,         nan])

In [48]:
np.isnan(np.log10(arr10))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([False, False, False,  True,  True, False, False, False, False,
       False,  True,  True])

### np.logical_not(arr), np.logical_and(arr1, arr2), np.logical_or(arr1, arr2), np.logical_xor(arr1, arr2)
#### NÃO lógico, E lógico, OU lógico e OU Exclusivo respectivamente.

In [49]:
np.logical_not(np.isnan(np.log10(arr10)))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([ True,  True,  True, False, False,  True,  True,  True,  True,
        True, False, False])

In [50]:
np.logical_and(arr6, arr20)

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

### np.cos(arr), np.sin(arr), np.tan(arr), np.cosh(arr) ...
#### Métodos trigonométricos para arrays. Os valores devem ser radianos.

In [51]:
np.round(np.cos(np.array([0, np.pi/4, np.pi/2, np.pi, 2 * np.pi])), 2)

array([ 1.  ,  0.71,  0.  , -1.  ,  1.  ])

-------------------------------------------------------------------------------------------------------

## Álgebra Linear com .linalg

### np.linalg.det(arr)
#### Calcula o determinante de arr.

In [52]:
A = np.array([[1, 1, 3], [1, 0, -1], [1, -2, 1]])
A

array([[ 1,  1,  3],
       [ 1,  0, -1],
       [ 1, -2,  1]])

In [53]:
np.linalg.det(A)

-10.000000000000002

### np.linalg.eig(arr)
#### Calcula os auto-vetores de arr.

In [54]:
np.linalg.eig(A)

(array([ 2.23606798, -2.23606798,  2.        ]),
 array([[ 0.91632011,  0.65809173, -0.91287093],
        [ 0.28315849, -0.5324074 , -0.36514837],
        [ 0.28315849, -0.5324074 , -0.18257419]]))

### np.linalg.inv(arr)
#### Calcula a inversa de arr.

In [55]:
C = np.linalg.inv(A)
C

array([[ 0.2,  0.7,  0.1],
       [ 0.2,  0.2, -0.4],
       [ 0.2, -0.3,  0.1]])

In [56]:
# Por definição a produto escalar de uma matriz quadrada de ordem n pela sua inversa deve sempre resultar
# em uma matriz identidade também de ordem n.

np.round(A.dot(C), 0) # Prova real.

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0.,  0.,  1.]])

### np.linalg.solve(A, B)
#### Resolve o sistema matricial A.X = B.

In [57]:
B = np.array([6, 5, 3])
B

array([6, 5, 3])

In [58]:
X = np.linalg.solve(A, B)
X

array([5.00000000e+00, 1.00000000e+00, 1.66533454e-17])

In [59]:
A.dot(X) == B # Prova real.

array([ True,  True,  True])

-------------------------------------------------------------------------------------------------------

## Álgebra Linear com métodos instanciados.

### arr.trace()
#### Calcula o traço de arr. O traço é a soma dos elementos da diagonal principal.

In [60]:
A

array([[ 1,  1,  3],
       [ 1,  0, -1],
       [ 1, -2,  1]])

In [61]:
A.trace()

2

### arr.diagonal()
#### Devolve uma nova array com os elementos da diagonal principal de arr.

In [62]:
A.diagonal()

array([1, 0, 1])

### arr1.dot(arr2)
#### Faz o produto escalar arr1 . arr2

In [63]:
A.dot(np.array([1, 2, 3]))

array([12, -2,  0])

-------------------------------------------------------------------------------------------------------

## Ordenação

### np.sort(arr)
#### Ordena arr em ordem crescente.

In [64]:
arr18

array([1, 2, 8, 9, 5])

In [65]:
np.sort(arr18) # Ordem crescente.

array([1, 2, 5, 8, 9])

In [66]:
np.sort(arr18)[::-1] # Ordem decrescente.

array([9, 8, 5, 2, 1])

### sort()
#### Ordena a instância in-place.

In [67]:
arr18.sort()

In [68]:
arr18

array([1, 2, 5, 8, 9])

-------------------------------------------------------------------------------------------------------

## Máximo e Mínimo

### arr.max() e arr.min()
#### Encontra o valor máximo e mínimo de arr respectivamente.

In [69]:
arr18

array([1, 2, 5, 8, 9])

In [70]:
arr18.max()

9

In [71]:
arr18.min()

1

-------------------------------------------------------------------------------------------------------

## Concatenação, repetição, divisão e seleção.

### np.concatenate([arr1, arr2, ..., arrn]), np.vstack() e np.hstack()
#### Concatenam arr1, arr2, ..., arrn ao longo de um eixo, vstack no eixo vertical (0) e hstack no eixo horizontal (1).

In [72]:
arr17

array([ 6,  7,  8,  9, 10])

In [73]:
arr18

array([1, 2, 5, 8, 9])

In [74]:
np.concatenate([arr17, arr18])

array([ 6,  7,  8,  9, 10,  1,  2,  5,  8,  9])

In [75]:
np.hstack([arr17, arr18])

array([ 6,  7,  8,  9, 10,  1,  2,  5,  8,  9])

In [76]:
np.vstack([arr17, arr18])

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  5,  8,  9]])

### arr.repeat(n) e np.tile(arr, [mxn])
#### Repete os elementos de arr n vezes e repete arr mxn vezes, respectivamente.

In [77]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr3.repeat(2) # O resultado é linearizado pois a dimensão original não comporta a nova quantidade de dados.

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [79]:
np.tile(arr3, 2)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [80]:
np.tile(arr3, [2, 1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
np.tile(arr3, [3, 3])

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

### np.split(arr, [índices])
#### Divide arr nos índices definidos, gerando len(índices) + 1 novas arrays.

In [82]:
arr14

array([3, 2, 6, 4, 9, 0, 8, 7, 5, 1])

In [83]:
np.split(arr14, [3, 6])

[array([3, 2, 6]), array([4, 9, 0]), array([8, 7, 5, 1])]

In [84]:
arr14_split_1, arr14_split_2 = np.split(arr14, [5])

In [85]:
arr14_split_1

array([3, 2, 6, 4, 9])

In [86]:
arr14_split_2

array([0, 8, 7, 5, 1])

### arr.take([índices]) e arr.put([índices], n)
#### Seleciona os índices de arr e substitui os valores nestes índices por n, respectivamente.

In [87]:
arr10

array([ 0.83429264,  0.74186803,  0.69985913, -1.487009  , -0.09688481,
        0.78347656,  0.52668533,  0.36383321,  1.50956084,  1.22761428,
       -1.05334284, -0.30188628])

In [88]:
arr10.take([0, 4, -1])

array([ 0.83429264, -0.09688481, -0.30188628])

In [89]:
arr10.put([-3, 5, 2], 0)

In [90]:
arr10

array([ 0.83429264,  0.74186803,  0.        , -1.487009  , -0.09688481,
        0.        ,  0.52668533,  0.36383321,  1.50956084,  0.        ,
       -1.05334284, -0.30188628])